# Generated by Django 5.2 on 2025-04-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_vendorprofile_date_of_birth_vendorprofile_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='vendor_profile_verified',
            field=models.BooleanField(default=False),
        ),
    ]
