# Generated by Django 5.2 on 2025-05-01 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_vendorprofile_vendor_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
