# Generated by Django 5.2 on 2025-07-24 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_vendorprofile_user'),
        ('market_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAdministratorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorManagerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('districts', models.ManyToManyField(blank=True, related_name='vendor_managers', to='market_intelligence.district')),
                ('regions', models.ManyToManyField(blank=True, related_name='vendor_managers', to='market_intelligence.region')),
                ('towns', models.ManyToManyField(blank=True, related_name='vendor_managers', to='market_intelligence.town')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
