# Generated by Django 5.2 on 2025-04-29 14:30

import core.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_expiry_minutes', models.PositiveSmallIntegerField(default=10, help_text='Minutes before an e-mail OTP expires.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('support_email', models.EmailField(default='support@example.com', max_length=254)),
                ('throttle_anon_per_min', models.PositiveSmallIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('user_email', 'User e-mail verification'), ('user_phone', 'User phone verification'), ('business_email', 'Business e-mail verification'), ('business_phone', 'Business phone verification')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS')], max_length=10)),
                ('code', models.CharField(db_index=True, max_length=8)),
                ('target', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=core.models.expiry_default)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'purpose', 'verified')},
            },
        ),
    ]
