# Generated by Django 5.2 on 2025-04-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_otp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(choices=[('user_email', 'User e-mail verification'), ('user_phone', 'User phone verification'), ('business_email', 'Business e-mail verification'), ('business_phone', 'Business phone verification'), ('password_reset', 'Password Reset')], max_length=30),
        ),
    ]
