# Generated by Django 5.2 on 2025-05-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service_management', '0002_category_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
