# Generated by Django 5.2 on 2025-05-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service_management', '0003_alter_attributes_description_alter_attributes_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product_service_management.sku'),
        ),
    ]
