# Generated by Django 5.2 on 2025-06-16 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_service_management', '0004_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(blank=True, choices=[('product', 'Product'), ('service', 'Service')], db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product_service_management.attributes'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type': 'product'}, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product_service_management.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product_service_management.productcondition'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='product_service_management.productservicestatus'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='product_service_management.tag'),
        ),
        migrations.AlterField(
            model_name='service',
            name='attributes',
            field=models.ManyToManyField(blank=True, null=True, to='product_service_management.attributes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(limit_choices_to={'type': 'service'}, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='product_service_management.category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='product_service_management.tag'),
        ),
    ]
