# Generated by Django 5.2 on 2025-07-29 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_business_description'),
        ('market_intelligence', '0001_initial'),
        ('product_service_management', '0005_category_type_alter_product_attributes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='business',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='service',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='service',
            name='business',
        ),
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.RemoveField(
            model_name='service',
            name='district',
        ),
        migrations.RemoveField(
            model_name='service',
            name='pricing_type',
        ),
        migrations.RemoveField(
            model_name='service',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='service',
            name='regions',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='service',
            name='town',
        ),
        migrations.CreateModel(
            name='GenericProduct',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'product'}, on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_products', to='product_service_management.category')),
            ],
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_service_management.genericproduct'),
        ),
        migrations.CreateModel(
            name='GenericService',
            fields=[
                ('service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(limit_choices_to={'type': 'service'}, on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_services', to='product_service_management.category')),
            ],
        ),
        migrations.AlterField(
            model_name='serviceimage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_service_management.genericservice'),
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True)),
                ('listing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.ManyToManyField(blank=True, to='product_service_management.attributes')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to='business.business')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_listings', to='product_service_management.productcondition')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='product_service_management.genericproduct')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catalogue_products', to='product_service_management.sku')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_listings', to='product_service_management.productservicestatus')),
                ('tags', models.ManyToManyField(blank=True, to='product_service_management.tag')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_product_image/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vendor_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_service_management.vendorproduct')),
            ],
        ),
        migrations.CreateModel(
            name='VendorService',
            fields=[
                ('vendor_service_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attributes', models.ManyToManyField(blank=True, to='product_service_management.attributes')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_listings', to='business.business')),
                ('districts', models.ManyToManyField(blank=True, related_name='vendor_services', to='market_intelligence.district')),
                ('pricing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_service_listings', to='product_service_management.servicepricingchoices')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_listings', to=settings.AUTH_USER_MODEL)),
                ('regions', models.ManyToManyField(blank=True, related_name='vendor_services', to='market_intelligence.region')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='product_service_management.genericservice')),
                ('tags', models.ManyToManyField(blank=True, to='product_service_management.tag')),
                ('towns', models.ManyToManyField(blank=True, related_name='vendor_services', to='market_intelligence.town')),
            ],
        ),
        migrations.CreateModel(
            name='VendorServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vendor_service_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('vendor_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product_service_management.vendorservice')),
            ],
        ),
    ]
