# Generated by Django 5.2 on 2025-07-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0002_alter_cartitem_product'),
        ('checkout_processing', '0009_alter_directbooking_service_and_more'),
        ('product_service_management', '0006_remove_product_attributes_remove_product_business_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['seller', 'is_active'], name='product_ser_seller__fdb183_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorproduct',
            index=models.Index(fields=['product', 'price'], name='product_ser_product_290d30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorproduct',
            unique_together={('product', 'seller', 'business')},
        ),
        migrations.AddIndex(
            model_name='vendorservice',
            index=models.Index(fields=['provider', 'is_active'], name='product_ser_provide_fb1c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorservice',
            index=models.Index(fields=['service', 'price'], name='product_ser_service_cb2e38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorservice',
            unique_together={('service', 'provider', 'business')},
        ),
    ]
