# Generated by Django 5.2 on 2025-05-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_content_type_feedback_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackresponse',
            name='re',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='feedback.feedback'),
        ),
    ]
