# Generated by Django 5.2 on 2025-07-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('feedback', '0003_feedbackresponse_re'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'product_service_management'), ('model__in', ('vendorproduct', 'vendorservice'))), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
