# Generated by Django 5.2 on 2025-05-07 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_processing', '0001_initial'),
        ('market_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorder',
            old_name='locations',
            new_name='location',
        ),
        migrations.AddField(
            model_name='directorder',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directorder',
            name='town',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='directorder',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_intelligence.district'),
        ),
        migrations.AlterField(
            model_name='directorder',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='market_intelligence.region'),
        ),
    ]
