# Generated by Django 5.2 on 2025-05-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_processing', '0003_directbooking_vendornotification'),
        ('product_service_management', '0003_alter_attributes_description_alter_attributes_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendornotification',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_booking_notifications', to='product_service_management.service'),
        ),
        migrations.AlterField(
            model_name='vendornotification',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vendornotification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_orders_notifications', to='product_service_management.product'),
        ),
        migrations.AlterField(
            model_name='vendornotification',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
