# Generated by Django 5.2 on 2025-05-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_processing', '0004_vendornotification_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorder',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='directorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='directorder',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
