# Generated by Django 5.2 on 2025-05-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_processing', '0005_alter_directorder_city_alter_directorder_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorder',
            name='google_map_url',
            field=models.URLField(blank=True, help_text='A Google Maps link (e.g. the ‘share’ URL) for this address', null=True),
        ),
    ]
