# Generated by Django 5.2 on 2025-06-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_processing', '0007_directbooking_status_directorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
