# Generated by Django 5.2 on 2025-07-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_processing', '0008_alter_directorder_status'),
        ('product_service_management', '0006_remove_product_attributes_remove_product_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directbooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_bookings', to='product_service_management.vendorservice'),
        ),
        migrations.AlterField(
            model_name='directorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='direct_orders', to='product_service_management.vendorproduct'),
        ),
        migrations.AlterField(
            model_name='vendornotification',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_orders_notifications', to='product_service_management.vendorproduct'),
        ),
        migrations.AlterField(
            model_name='vendornotification',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_booking_notifications', to='product_service_management.vendorservice'),
        ),
    ]
