# Generated by Django 5.2 on 2025-05-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_remove_business_city_business_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_type',
        ),
    ]
