# Generated by Django 5.2 on 2025-05-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_remove_business_business_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='business_presence',
        ),
    ]
