# Generated by Django 5.2 on 2025-05-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_remove_business_business_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_description',
            field=models.TextField(blank=True),
        ),
    ]
