# Generated by Django 5.2 on 2025-07-29 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_management', '0001_initial'),
        ('product_service_management', '0006_remove_product_attributes_remove_product_business_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_service_management.vendorproduct'),
        ),
    ]
